### ISSUE TITLE
Objects in play area can completely overlap

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-pairs#122]
**Test device**
MacBook Air (M1 chip)

**Operating System**
15.3.1

**Browser**
Safari 18.3.1

**Problem description**
For https://github.com/phetsims/qa/issues/1219, on the Intro screen, it is possible for the total to not match the number of objects on the screen. 

**Steps to reproduce**
There are probably a lot of extra steps here, but this is how I can reproduce the bug reliably:
1. On the Intro Screen, press the commutativeButton
2. Change total to 4 and press the commutativeButton
3. Change total to 7and press the commutativeButton
4. change total back to 3 and press the commutativeButton
5. Change total to 8 -- number of objects might not match total at this point, if they still match continue on....
6. Change total to 7 and press the commutativeButton 3 times
7. Change total to 9 --total is incorrect

**Visuals**
In this video I was able to get the bug at step 5:

https://github.com/user-attachments/assets/453e2c79-2b79-4945-bb07-a1d742b63e8b

**Comment by Nancy-Salpepi** [comment]
This also happens on the Twenty screen following the same steps, but with 13, 14, 17, and 18.

<img width="1190" alt="Image" src="https://github.com/user-attachments/assets/47154ba4-195d-4bad-98c9-a23509614703" />

**Comment by catherinecarter** [comment]
I followed the steps and found two objects exactly on top of each other. So the total number of objects (I think) actually is correct, but you have to move all of them to find the hidden one. 

https://github.com/user-attachments/assets/9e6f32bb-c128-4468-8fa2-42f489c7cc5f

**Comment by catherinecarter** [comment]
No worries! Yes, they should repel so they're not on top of each other. I found a similar instance in a different way in #117.

**Comment by marlitas** [comment]
Oh my gosh. haha just came in to talk about that! Yes thank goodness this is not something else because I was about to be very scared 😆 

This is a slightly different interaction than #117 since nothing is being dropped, but this should not be happening. I will work on that. Thanks!

**Comment by Nancy-Salpepi** [comment]
Yeah....let's change this title.

**Comment by marlitas** [comment]
I updated the behavior in the above commit. I used a recursive function for this that I think can actually be applied to potentially improve https://github.com/phetsims/number-pairs/issues/117 as well. I would like @pixelzoom to review though before moving forward on that.

Also, @Nancy-Salpepi can you confirm that this is fixed on main?

**Comment by Nancy-Salpepi** [comment]
I still saw it on the Twenty Screen with same steps as original using 13,14,17,18,19 instead. 

<img width="1073" alt="Image" src="https://github.com/user-attachments/assets/27842c4d-fddb-4e75-9b82-aec119daa31a" />

**Comment by pixelzoom** [comment]
https://github.com/phetsims/number-pairs/commit/18a16469c3f2efe2ef0f5e341b08aaecc529d0f9 looks good.  

One suggestion, and I don't feel too strongly about whether you implement it... For `handleLocationOverlap` (and recursive functions in general) you might want to build in something to protect against programming errors (current or future) that result in infinite recursion.  For example, if there's a maximum (or even reasonable) depth of the recursion, add an assertion to make sure that you don't exceed that depth.

**Comment by marlitas** [comment]
Thanks @pixelzoom, I went ahead and added that assertion and also added some documentation for additional clarity. 

@Nancy-Salpepi I also committed a fix. It was a small change that caused some things to be overlooked in higher quantities. I think I would like to keep this open either way to double check in the upcoming dev test.

**Comment by marlitas** [comment]
This actually can be replicated through just the last three steps:

- Switch to 9
- Move 5 beads at once from the left side all the way to the left
- Press commutativeButton

I believe this is handled above. It changes a small part of the logic on the commutative button for the beads, so let's keep an eye on that. 

@Nancy-Salpepi can you see if this problem is at least fixed on main? Let's keep the issue open for RC though.

**Comment by Nancy-Salpepi** [comment]
I still see the issue on the Twenty Screen with the apples following my laundry list of steps in the original comment with the "teen" version of the numbers (11, 14, 17 etc).

**Comment by marlitas** [comment]
Okay. This is done and I tried the teen steps and it looks fixed. @Nancy-Salpepi can you confirm?

**Comment by Nancy-Salpepi** [comment]
This looks fixed now! I am going to go ahead and close.

**Comment by Nancy-Salpepi** [comment]
Sorry. I'm going to reopen this. I found an edge case where it happens again:

Steps:
1. On the Intro Screen, select 10 with pointer
2. Press the 10 Frame button with pointer
3. Press Tab so the Apples have focus
4. Use keyboard  nav to highlight and then select the 1 Apple on the right side
5. Press Commutative button with pointer 

<img width="1067" alt="Image" src="https://github.com/user-attachments/assets/6f649e04-18d1-46c3-a2bd-cca4ce17c6bd" />

**Comment by marlitas** [comment]
This was a great edge case. Nice find @Nancy-Salpepi! I believe it is addressed above and now ready for cherry pick.

**Comment by KatieWoe** [comment]
The issues describe seem to be fixed in rc.2. I still see #117 but if that's acceptable this can be closed.

**Comment by marlitas** [comment]
That seems acceptable! I think we can close. Thanks :-)
