### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-pairs#159]
For https://github.com/phetsims/qa/issues/1237. On Win 11 Chrome.
The memory test on the rc revealed what looks like a memory leak.

<img width="362" alt="Image" src="https://github.com/user-attachments/assets/6cb12522-2bce-4339-9187-6644ebe12cc2" />

**Comment by marlitas** [comment]
oh boy... I'll start taking a look.

**Comment by marlitas** [comment]
Okay I think this was actually fixed by a string related bug that JO and I were investigating. I was able to reproduce a memory leak with a build without that fix and then another build with that fix showed no memory leak. That feels like enough for me to go on that this commit will patch it up: https://github.com/phetsims/number-pairs/commit/cdd3f0b9a67551e1875ad7b0e39553970e6f3b10

**Comment by KatieWoe** [comment]
I still see a memory leak in rc.2

<img width="362" alt="Image" src="https://github.com/user-attachments/assets/0714b986-7743-44fb-916a-18ea760fd420" />

**Comment by marlitas** [comment]
hmmm... taking a look.

**Comment by marlitas** [comment]
I'm really confused. I specifically remember passing a memory leak test multiple times on both a built and unbuilt version of the sim on April 9th. I have checked every commit after that point, compared that memory heap snapshots, commented out code, omitted files to try and suss out where this leak could be coming from.

I now have done a memory leak on each individual screen to see if there's a specific representation that is leaking, but each individual screen indicates there is no memory leak. One such example from screen 20 which includes all the representations is below. However, a test of the full sim continues to indicate there is a memory leak... I'm not sure what to do at this point. I have spent about a full day worth of time trying to track this down which does not seem fruitful. @pixelzoom Is this something you might be able to help me with?

<img width="224" alt="Image" src="https://github.com/user-attachments/assets/dce86bab-1a03-47b8-baec-828c3f2c5940" />

**Comment by marlitas** [comment]
@pixelzoom between rc.1 and rc.2

The SHA I provided was the first commit after rc.1 was created.

**Comment by pixelzoom** [comment]
I'm confused.  @KatieWoe reports this for https://github.com/phetsims/qa/issues/1237, which is the first RC version, 1.0.0-rc.1.  But you said above that when you tested and saw no memory leak "We were in RC.1 by then".

**Comment by marlitas** [comment]
Yes @KatieWoe found the memory leak in rc.1. This commit: https://github.com/phetsims/number-pairs/commit/cdd3f0b9a67551e1875ad7b0e39553970e6f3b10 supposedly fixed the memory leak. @KatieWoe tested for a memory leak again in rc.2 and still sees one.

It is entirely possible that https://github.com/phetsims/number-pairs/commit/cdd3f0b9a67551e1875ad7b0e39553970e6f3b10 didn't actually fix the memory leak, but I have a very clear memory of finding a memory leak before that commit and not seeing one after. I unfortunately did not take pictures of those test results.

**Comment by pixelzoom** [comment]
So it looks like RC.1 and RC.2 have a similar memory leak that may not be fixed.  And in https://github.com/phetsims/number-pairs/issues/159#issuecomment-2825054201 you're reporting that changes made after publishing RC.2 have resulted in a worse memory leak.  Do I understand that correctly? 

> I now have done a memory leak on each individual screen to see if there's a specific representation that is leaking, but each individual screen indicates there is no memory leak. 

Are the results that you're showing for a version that was built using the memory-test protocol, or for unbuilt?  1.0 branch or main?

**Comment by marlitas** [comment]
I did all my memory testing on main. I first confirmed that I could reproduce the memory test results that @KatieWoe found on main before determining if I needed to do a build during debugging/investigation. Since I was clearly able to reproduce the memory leak on main multiple times, building each time did not feel necessary.

Scenarios I tested that still revealed a memory leak:

- No RichText phrase in the accordion box
- ModalsDisabled

Scenarios I tested that revealed no memory leak:

- NumberPlay (this confirmed it is not a leak in the speech synthesis features)
- Each individual screen (not sure what this means)

**Comment by marlitas** [comment]
> And do you see the same leak in 1.0 and main?

Yes I see the same leak in both places.

> changes made after publishing RC.2 have resulted in a worse memory leak

I don't know if it's worse... It seems like it might be the same.

**Comment by pixelzoom** [comment]
I'm having a difficult time making any progress on this issue.  The most common leak would be LocalizedStringProperty listener that is not cleaned up, due to some DerivedProperty, Text, or RichText not being disposed.  The most logical way to identify that type of leak would be `?listenerLimit` -- but there are still general problems with that, see https://github.com/phetsims/axon/issues/462.  Hacking my way around it by opting out of `listenerLimit` for `localeProperty`, I then ran into `listenerLimit` problems with scenery TransformTracker.  I don't know if that's a leak or if there really are a huge number of Nodes in the transform Trail.

**Comment by pixelzoom** [comment]
Possible common-code leak in InteractiveHighlighting, see https://github.com/phetsims/scenery/issues/1706.

**Comment by pixelzoom** [comment]
@marlitas here's a patch that will let you selectively opt in to `?listenerLimit` for suspicious Properties.  The patch opts in for all LocalizedStringProperty instances.  

<details>
<summary>patch</summary>

```diff
Subject: [PATCH] opt in to listenerLimit
---
Index: chipper/js/browser/LocalizedStringProperty.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/chipper/js/browser/LocalizedStringProperty.ts b/chipper/js/browser/LocalizedStringProperty.ts
--- a/chipper/js/browser/LocalizedStringProperty.ts	(revision 5b02aa25fc50f00b235b7e83636eb47b79a5d01c)
+++ b/chipper/js/browser/LocalizedStringProperty.ts	(date 1745863988638)
@@ -37,6 +37,7 @@
 
       // This property should update the localizedString's TinyProperty too.
       bidirectional: true,
+      enableListenerLimit: true,
 
       // phet-io issues
       phetioValueType: StringIO,
Index: axon/js/TinyProperty.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/axon/js/TinyProperty.ts b/axon/js/TinyProperty.ts
--- a/axon/js/TinyProperty.ts	(revision 7339accb2a1a19dc266b48e4d15ea006e88a8754)
+++ b/axon/js/TinyProperty.ts	(date 1745864589727)
@@ -34,13 +34,14 @@
 
   public constructor( value: T, onBeforeNotify?: OptionsAlias<T>['onBeforeNotify'] | null,
                       hasListenerOrderDependencies?: OptionsAlias<T>['hasListenerOrderDependencies'] | null,
-                      reentrantNotificationStrategy?: OptionsAlias<T>['reentrantNotificationStrategy'] | null ) {
+                      reentrantNotificationStrategy?: OptionsAlias<T>['reentrantNotificationStrategy'] | null,
+                      enableListenerLimit = false ) {
 
     // Defaults to "queue" for Properties so that we notify all listeners for a value change
     // before notifying for the next value change. For example, if we change from a->b, and one listener changes the value
     // from b->c, that reentrant value change will queue its listeners for after all listeners have fired for a->b. For
     // specifics see documentation in TinyEmitter.
-    super( onBeforeNotify, hasListenerOrderDependencies, reentrantNotificationStrategy || 'queue' );
+    super( onBeforeNotify, hasListenerOrderDependencies, reentrantNotificationStrategy || 'queue', enableListenerLimit );
 
     this._value = value;
   }
Index: axon/js/TinyEmitter.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/axon/js/TinyEmitter.ts b/axon/js/TinyEmitter.ts
--- a/axon/js/TinyEmitter.ts	(revision 7339accb2a1a19dc266b48e4d15ea006e88a8754)
+++ b/axon/js/TinyEmitter.ts	(date 1745864538528)
@@ -107,10 +107,15 @@
   // During emit() keep track of iteration progress and guard listeners if mutated during emit()
   private emitContexts: EmitContext<T>[] = [];
 
+  private readonly enableListenerLimit: boolean;
+
   // Null on parameters is a no-op
   public constructor( onBeforeNotify?: TinyEmitterOptions<T>['onBeforeNotify'] | null,
                       hasListenerOrderDependencies?: TinyEmitterOptions<T>['hasListenerOrderDependencies'] | null,
-                      reentrantNotificationStrategy?: TinyEmitterOptions<T>['reentrantNotificationStrategy'] | null ) {
+                      reentrantNotificationStrategy?: TinyEmitterOptions<T>['reentrantNotificationStrategy'] | null,
+                      enableListenerLimit = false ) {
+
+    this.enableListenerLimit = enableListenerLimit;
 
     if ( onBeforeNotify ) {
       this.onBeforeNotify = onBeforeNotify;
@@ -246,7 +251,7 @@
 
     this.changeCount && this.changeCount( 1 );
 
-    if ( assert && listenerLimit && isFinite( listenerLimit ) && maxListenerCount < this.listeners.size ) {
+    if ( assert && this.enableListenerLimit && listenerLimit && isFinite( listenerLimit ) && maxListenerCount < this.listeners.size ) {
       maxListenerCount = this.listeners.size;
       console.log( `Max TinyEmitter listeners: ${maxListenerCount}` );
       assert( maxListenerCount <= listenerLimit, `listener count of ${maxListenerCount} above ?listenerLimit=${listenerLimit}` );
Index: axon/js/ReadOnlyProperty.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/axon/js/ReadOnlyProperty.ts b/axon/js/ReadOnlyProperty.ts
--- a/axon/js/ReadOnlyProperty.ts	(revision 7339accb2a1a19dc266b48e4d15ea006e88a8754)
+++ b/axon/js/ReadOnlyProperty.ts	(date 1745864281538)
@@ -76,6 +76,9 @@
   // If specified as true, this flag will ensure that listener order never changes (like via ?listenerOrder=random)
   hasListenerOrderDependencies?: boolean;
 
+  // Whether to enable the ?listenerLimit query parameter for this Property.
+  enableListenerLimit?: boolean;
+
   // Changes the behavior of how listeners are notified in reentrant cases (where linked listeners cause this Property
   // to change its value again). Defaults to "queue" for Properties so that we notify all listeners for a value change
   // before notifying for the next value change. For example, if we change from a->b, and one listener changes the value
@@ -110,7 +113,7 @@
   public readonly validValues?: readonly T[];
 
   // emit is called when the value changes (or on link)
-  private tinyProperty: TinyProperty<T>;
+  private readonly tinyProperty: TinyProperty<T>;
 
   // whether we are in the process of notifying listeners; changed in some Property test files with @ts-expect-error
   private notifying: boolean;
@@ -146,6 +149,7 @@
       reentrant: false,
       hasListenerOrderDependencies: false,
       reentrantNotificationStrategy: 'queue',
+      enableListenerLimit: false,
 
       // See Validation.ts for ValueComparisonStrategy for available values. Please note that this will be used for
       // equality comparison both with validation (i.e. for validValue comparison), as well as determining if the
@@ -201,7 +205,8 @@
 
     this.validValues = options.validValues;
 
-    this.tinyProperty = new TinyProperty( value, null, options.hasListenerOrderDependencies, options.reentrantNotificationStrategy );
+    this.tinyProperty = new TinyProperty( value, null, options.hasListenerOrderDependencies,
+      options.reentrantNotificationStrategy, options.enableListenerLimit );
 
     // Since we are already in the heavyweight Property, we always assign TinyProperty.valueComparisonStrategy for clarity.
     this.tinyProperty.valueComparisonStrategy = options.valueComparisonStrategy;
```

</details>

**Comment by marlitas** [comment]
I have had zero success or leads... I initially tried to enable listener limit on a file by file basis, but that was becoming very tedious and felt unproductive, especially since I have no guarantees that this is a leak in the sim itself. I did find that we have two localeProperties in this sim outside of the singleton and limited the listener limit to that locale Property, but nothing.

I have reached out to @jonathanolson to see if he can help me decipher the memory heap comparisons.

**Comment by jonathanolson** [comment]
Initial investigation is showing that (a) this is not leaking on Firefox (or what it is reporting), and may be Blink-specific (and potentially browser-version-specific), and (b) the leak is Blink-side within the "Other non-JS objects" section. There seems to be potential minimal leaks that aren't significant in other regions.

<img width="521" alt="Image" src="https://github.com/user-attachments/assets/60181a8a-8d77-4af1-a173-a06665e93340" />

It seems like Safari's tools are showing the page memory significantly increasing:

<img width="841" alt="Image" src="https://github.com/user-attachments/assets/6cbdf78c-6457-4f03-8bbc-5ba28d665ae8" />

I'll be looking more into this, since it is likely something we are doing with interacting with the DOM (@jessegreenberg have we changed anything recently with DOM interaction?).

It will be good to check if it is sim-specific or a general issue. I'll also try disabling certain features to see if that helps, and likely using bisection to determine when this memory usage started happening.

**Comment by jessegreenberg** [comment]
Possibly, `accessibleHeading` and `accessibleParagraph` come to mind as the most recent changes. It is possible we are not cleaning up those elements correctly. I will take a look.

**Comment by jessegreenberg** [comment]
I did some more testing this evening but results are confusing.

One test of the all_phet version. Snapshots taken every ten minutes. 

<details>

![Image](https://github.com/user-attachments/assets/f4e59cfd-ff39-485c-94cd-fa065f479c1e)

</details>

In the 137 MB snapshot Chrome reports a string that is 10.5MB(!!) and looks like this:

![Image](https://github.com/user-attachments/assets/451592b5-7beb-4872-ad85-feff769b7ca5)

One test of the en_phet version. Snapshots taken every 10 minutes. It only grew to 141MB.

<details>

![Image](https://github.com/user-attachments/assets/278e7e82-3f09-43b2-877e-c1b30da023dd)
</details>

I can't find anything else useful when comparing snapshots.

Testing rc.1 again with all_phet shows similar leak to a main

<details>

![Image](https://github.com/user-attachments/assets/331da5ad-127e-44ea-a466-7b82fc8451e9)

</details>

But I am confused because summing up all entries in the "Size Delta" column between snapshots 2 and 3 produces <1MB of growth while Chrome reports ~60MB.

**Comment by marlitas** [comment]
Doing a variety of testing. It looks like there is a memory leak in Trig Tour as well:
<img width="730" alt="Image" src="https://github.com/user-attachments/assets/f51da2ed-3c50-4415-872e-e0acb8c90686" />

**Comment by KatieWoe** [comment]
This https://github.com/phetsims/qa/issues/1222#issuecomment-2707535043 is the latest Trig Tour mem test QA did, which it passed. It was published right after this test. So something may have happened in an MR?

**Comment by marlitas** [comment]
> It was published right after this test. So something may have happened in an MR?

Sorry I should have clarified that memory test was done on main. I updated the comment to reflect that.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/number-pairs/issues/159#issuecomment-2840726664 also made me question the accuracy of results from Chrome dev tools.

**Comment by marlitas** [comment]
I'm so confused... I updated but I'm still seeing this on the published Number Line Integers:

<img width="587" alt="Image" src="https://github.com/user-attachments/assets/661eec5c-f013-4989-b685-e866134cf682" />

**Comment by marlitas** [comment]
(Unbuilt) Number Pairs test on Safari for about 5 minutes:

<img width="1544" alt="Image" src="https://github.com/user-attachments/assets/597a866f-6e38-409e-bb46-a2461be4526c" />

(Published) Number Line Integers Test on Safari for 5 minutes:

<img width="1541" alt="Image" src="https://github.com/user-attachments/assets/eb420aba-6e44-4207-8ae5-f7d6f01a3b34" />


Both show a steady growth in the page memory? My next step is to fuzz on an ipad and see if it crashes.

**Comment by marlitas** [comment]
Based on https://github.com/phetsims/chipper/issues/1586 I believe this memory leak is not sim specific and is mostly out of our hands. We are still not confident in what is causing the leak, but it does not appear to be PhET related code. Closing. Thanks for everyone's work here!
