### ISSUE TITLE
Solidify layout of number buttons and counting area

### ISSUE THREAD

**Issue by samreid** [phetsims/number-pairs#208]
<img width="1789" height="1234" alt="Image" src="https://github.com/user-attachments/assets/e84d8340-bf68-4ebf-8fa0-ad8f81be429f" />

We should make it an option to specify the bounds of the counting area. This could change how the tens frame layout code works. Also check the functions in CountingObjectsManager to see if anything else needs to be updated.

**Comment by marlitas** [comment]
Here's a patch that allows for some quick demos of different button layout options:

<details>

```diff

Subject: [PATCH] Demo of some layout options for the game levels, see: https://github.com/phetsims/number-pairs/issues/208
---
Index: js/common/view/NumberEquationNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/NumberEquationNode.ts b/js/common/view/NumberEquationNode.ts
--- a/js/common/view/NumberEquationNode.ts	(revision 8bedae19fec7839cadec686bccb4b16baae5ce2a)
+++ b/js/common/view/NumberEquationNode.ts	(date 1758672087546)
@@ -75,8 +75,8 @@
       spacing: 10
     } );
 
+    options.children = [ contentNode ];
     super( options );
-    this.addChild( contentNode );
 
     // Expose references so callers (e.g., LevelNode) can adjust stroke/lineDash
     this.totalSquare = totalSquare;
Index: js/game/model/GameModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/game/model/GameModel.ts b/js/game/model/GameModel.ts
--- a/js/game/model/GameModel.ts	(revision 8bedae19fec7839cadec686bccb4b16baae5ce2a)
+++ b/js/game/model/GameModel.ts	(date 1758670735874)
@@ -17,6 +17,7 @@
 import Challenge from './Challenge.js';
 import Level from './Level.js';
 import RepresentationType from '../../common/model/RepresentationType.js';
+import NumberPairsConstants from '../../common/NumberPairsConstants.js';
 
 type SelfOptions = EmptySelfOptions;
 
@@ -70,7 +71,7 @@
        * Number Bond
        * - On first challenge, neither addend is zero
        */
-      new Level( 1, 'Missing addends in a number bond (0-10)', true, false, 'zeroToTen', 'bond', ( isFirst: boolean ): Challenge => {
+      new Level( 1, 'Missing addends in a number bond (0-10)', true, false, NumberPairsConstants.TEN_NUMBER_LINE_RANGE, 'bond', ( isFirst: boolean ): Challenge => {
         const y = dotRandom.nextIntBetween( isFirst ? 2 : 1, 10 ); // first: y>=2 so a,b>0 possible
         const a = dotRandom.nextIntBetween( isFirst ? 1 : 0, y - 1 ); // first: a>0
         return new Challenge( dotRandom.sample( [ 'a', 'b' ] as const ), a, y - a, y );
@@ -87,7 +88,7 @@
        * - The counting area can be hidden
        * Starting state is the counting area visible // TODO https://github.com/phetsims/number-pairs/issues/36
        */
-      new Level( 2, 'Missing addend in a number bond (10 only)', true, true, 'zeroToTen', 'bond', createLevel234Challenge, {
+      new Level( 2, 'Missing addend in a number bond (10 only)', true, true, NumberPairsConstants.TEN_NUMBER_LINE_RANGE, 'bond', createLevel234Challenge, {
         representationType: RepresentationType.KITTENS,
         tandem: tandem.createTandem( 'level2' )
       } ),
@@ -97,7 +98,7 @@
        *
        * Identical to level 2, except the representation of the decomposition is an equation
        */
-      new Level( 3, 'Missing addend in a decomposition equation', true, true, 'zeroToTen', 'decompositionEquation', createLevel234Challenge, {
+      new Level( 3, 'Missing addend in a decomposition equation', true, true, NumberPairsConstants.TEN_NUMBER_LINE_RANGE, 'decompositionEquation', createLevel234Challenge, {
         representationType: RepresentationType.KITTENS,
         tandem: tandem.createTandem( 'level3' )
       } ),
@@ -107,7 +108,7 @@
        *
        * Identical to Level 3, except the equation is flipped to represent a sum rather than a decomposition
        */
-      new Level( 4, 'Missing addend in a sum equation (10 only)', true, true, 'zeroToTen', 'sumEquation', createLevel234Challenge, {
+      new Level( 4, 'Missing addend in a sum equation (10 only)', true, true, NumberPairsConstants.TEN_NUMBER_LINE_RANGE, 'sumEquation', createLevel234Challenge, {
         representationType: RepresentationType.KITTENS,
         tandem: tandem.createTandem( 'level4' )
       } ),
@@ -119,7 +120,7 @@
        * * Ten frame (organize) button organizes into separate locations since this is a decomposition screen TODO:
        * https://github.com/phetsims/number-pairs/issues/36
        */
-      new Level( 5, 'Missing addend with a number bond (11-20)', true, true, 'zeroToTwenty', 'bond', ( isFirst: boolean ): Challenge => {
+      new Level( 5, 'Missing addend with a number bond (11-20)', true, true, NumberPairsConstants.TWENTY_NUMBER_LINE_RANGE, 'bond', ( isFirst: boolean ): Challenge => {
         const y = dotRandom.nextIntBetween( 11, 20 );
         const { a, b } = generateAddends( y, isFirst );
         return new Challenge( dotRandom.sample( [ 'a', 'b' ] as const ), a, b, y );
@@ -136,7 +137,7 @@
        * * Ten frame (organize) button organizes into two separate ten frames on left/right since this is decomposition
        *   ![][image185]
        */
-      new Level( 6, 'Missing addend with decomposition equation (11-20)', true, true, 'zeroToTwenty', 'decompositionEquation', ( isFirst: boolean ): Challenge => {
+      new Level( 6, 'Missing addend with decomposition equation (11-20)', true, true, NumberPairsConstants.TWENTY_NUMBER_LINE_RANGE, 'decompositionEquation', ( isFirst: boolean ): Challenge => {
         const y = dotRandom.nextIntBetween( 11, 20 );
         const { a, b } = generateAddends( y, isFirst );
         return new Challenge( dotRandom.sample( [ 'a', 'b' ] as const ), a, b, y );
@@ -154,7 +155,7 @@
        * * The missing component could be either addend or the total (i.e. any of a, b, or y could be missing)
        * * Value range for y is from 11-20
        */
-      new Level( 7, 'Missing addend or total with sum equation (11-20)', true, true, 'zeroToTwenty', 'sumEquation', ( isFirst: boolean ): Challenge => {
+      new Level( 7, 'Missing addend or total with sum equation (11-20)', true, true, NumberPairsConstants.TWENTY_NUMBER_LINE_RANGE, 'sumEquation', ( isFirst: boolean ): Challenge => {
         const y = dotRandom.nextIntBetween( 11, 20 );
         const { a, b } = generateAddends( y, isFirst );
         return new Challenge( dotRandom.sample( [ 'a', 'b', 'y' ] as const ), a, b, y );
@@ -170,7 +171,7 @@
        * - First challenge: left addend known, right addend unknown
        * - Subsequent challenges could be the left or the right addend (not the total)
        */
-      new Level( 8, 'Equations with the number line (0-20)', false, true, 'zeroToTwenty', 'numberLine', ( isFirst: boolean ): Challenge => {
+      new Level( 8, 'Equations with the number line (0-20)', false, true, NumberPairsConstants.TWENTY_NUMBER_LINE_RANGE, 'numberLine', ( isFirst: boolean ): Challenge => {
 
         // First challenge: y >= 2 so a,b > 0; subsequent: y can be 0..20 (allowing 0+0=0)
         const y = dotRandom.nextIntBetween( isFirst ? 2 : 0, 20 );
Index: js/game/model/Level.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/game/model/Level.ts b/js/game/model/Level.ts
--- a/js/game/model/Level.ts	(revision 8bedae19fec7839cadec686bccb4b16baae5ce2a)
+++ b/js/game/model/Level.ts	(date 1758670735889)
@@ -35,6 +35,7 @@
 import isSettingPhetioStateProperty from '../../../../tandem/js/isSettingPhetioStateProperty.js';
 import NumberPairsConstants from '../../common/NumberPairsConstants.js';
 import dotRandom from '../../../../dot/js/dotRandom.js';
+import Range from '../../../../dot/js/Range.js';
 
 type SelfOptions = {
   representationType: RepresentationType;
@@ -88,7 +89,7 @@
     public readonly description: string, // Appears in the bar at the top of the screen
     public readonly hasOrganizeTenFrameButton: boolean,
     public readonly hasEyeToggle: boolean,
-    public readonly range: InputRange,
+    public readonly range: Range,
     public readonly type: ChallengeType,
     private readonly createChallenge: ( isFirst: boolean ) => Challenge,
     providedOptions: LevelOptions
Index: js/game/view/LevelNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/game/view/LevelNode.ts b/js/game/view/LevelNode.ts
--- a/js/game/view/LevelNode.ts	(revision 8bedae19fec7839cadec686bccb4b16baae5ce2a)
+++ b/js/game/view/LevelNode.ts	(date 1758672422124)
@@ -38,6 +38,7 @@
 
 type SelfOptions = EmptySelfOptions;
 type LevelNodeOptions = SelfOptions & StrictOmit<NodeOptions, 'children'>;
+const BUTTONS_TOP = false; // REMEMBER: change columns to rows in NumberButtonGrid too
 
 export default class LevelNode extends Node {
 
@@ -59,9 +60,12 @@
     this.addChild( statusBar );
 
     // Number selection grid and selection state
-    const numberButtonGrid = new NumberButtonGrid( level.selectedGuessProperty, level.range, level.guessedNumbers, tandem.createTandem( 'numberButtonGrid' ) );
-    numberButtonGrid.centerX = layoutBounds.centerX;
-    numberButtonGrid.bottom = layoutBounds.bottom - 5;
+    const numberButtonGrid = new NumberButtonGrid( level.selectedGuessProperty, level.range, level.guessedNumbers, {
+      tandem: tandem.createTandem( 'numberButtonGrid' )
+    } );
+    numberButtonGrid.bottom = BUTTONS_TOP ? NumberPairsConstants.COUNTING_AREA_BOUNDS.top - NumberPairsConstants.COUNTING_AREA_Y_MARGIN :
+                              layoutBounds.bottom - NumberPairsConstants.SCREEN_VIEW_Y_MARGIN;
+    numberButtonGrid.right = BUTTONS_TOP ? NumberPairsConstants.COUNTING_AREA_BOUNDS.right : layoutBounds.right - NumberPairsConstants.SCREEN_VIEW_X_MARGIN;
     this.addChild( numberButtonGrid );
 
     // Correct-size adapter for bar model widths
@@ -69,6 +73,8 @@
 
     // Representation nodes (pre-create and swap based on challenge type)
     const bondNode = new GameNumberBondNode( level, level, {
+      bottom: NumberPairsConstants.COUNTING_AREA_BOUNDS.top - NumberPairsConstants.COUNTING_AREA_Y_MARGIN,
+      centerX: layoutBounds.centerX,
       visibleProperty: new DerivedProperty( [ NumberPairsPreferences.numberModelTypeProperty ], numberModelType => {
         return ( level.type !== 'decompositionEquation' && level.type !== 'sumEquation' ) && numberModelType === NumberModelType.NUMBER_BOND_MODEL;
       } )
@@ -77,6 +83,8 @@
       displayTotalNumberProperty: level.totalProperty,
       displayLeftAddendNumberProperty: level.leftAddendProperty,
       displayRightAddendNumberProperty: level.rightAddendProperty,
+      bottom: NumberPairsConstants.COUNTING_AREA_BOUNDS.top - NumberPairsConstants.COUNTING_AREA_Y_MARGIN,
+      centerX: layoutBounds.centerX,
       visibleProperty: new DerivedProperty( [ NumberPairsPreferences.numberModelTypeProperty ], numberModelType => {
         return ( level.type !== 'decompositionEquation' && level.type !== 'sumEquation' ) && numberModelType === NumberModelType.BAR_MODEL;
       } )
@@ -86,8 +94,16 @@
       totalColorProperty: NumberPairsColors.attributeSumColorProperty,
       leftAddendColorProperty: NumberPairsColors.attributeLeftAddendColorProperty,
       rightAddendColorProperty: NumberPairsColors.attributeRightAddendColorProperty,
-      visible: level.type === 'decompositionEquation' || level.type === 'sumEquation'
+      visible: level.type === 'decompositionEquation' || level.type === 'sumEquation',
+      bottom: NumberPairsConstants.COUNTING_AREA_BOUNDS.top - NumberPairsConstants.COUNTING_AREA_Y_MARGIN,
+      centerX: layoutBounds.centerX
     } );
+
+    if ( BUTTONS_TOP ) {
+      bondNode.left = NumberPairsConstants.COUNTING_AREA_BOUNDS.left;
+      barNode.left = NumberPairsConstants.COUNTING_AREA_BOUNDS.left;
+      equationNode.left = NumberPairsConstants.COUNTING_AREA_BOUNDS.left;
+    }
 
     this.addChild( bondNode );
     this.addChild( barNode );
@@ -108,13 +124,15 @@
     this.addChild( checkMark );
 
     ManualConstraint.create( this, [ bondNode, barNode, equationNode, statusBar, wrongMark, checkMark ], ( bondNodeProxy, barNodeProxy, equationNodeProxy, statusBarProxy, wrongMarkProxy, checkMarkProxy ) => {
-      bondNodeProxy.centerX = layoutBounds.centerX;
-      barNodeProxy.centerX = layoutBounds.centerX;
-      equationNodeProxy.centerX = layoutBounds.centerX;
 
-      bondNodeProxy.top = statusBarProxy.bottom + 5;
-      barNodeProxy.top = statusBarProxy.bottom + 5;
-      equationNodeProxy.top = statusBarProxy.bottom + 5;
+      // TODO: Why is the number model layout updating? https://github.com/phetsims/number-pairs/issues/208
+      // bondNodeProxy.centerX = layoutBounds.centerX;
+      // barNodeProxy.centerX = layoutBounds.centerX;
+      // equationNodeProxy.centerX = layoutBounds.centerX;
+      //
+      // bondNodeProxy.top = statusBarProxy.bottom + 5;
+      // barNodeProxy.top = statusBarProxy.bottom + 5;
+      // equationNodeProxy.top = statusBarProxy.bottom + 5;
 
       wrongMarkProxy.right = Math.max( bondNodeProxy.right, barNodeProxy.right, equationNodeProxy.right ) + 10;
       wrongMarkProxy.centerY = ( bondNodeProxy.centerY + barNodeProxy.centerY + equationNodeProxy.centerY ) / 3;
@@ -128,8 +146,7 @@
       const gameCountingAreaNode = new CountingAreaNode( new BooleanProperty( true ), new BooleanProperty( true ), level, {
         countingRepresentationTypeProperty: level.representationTypeProperty,
         backgroundColorProperty: NumberPairsColors.attributeSumColorProperty,
-        tandem: tandem.createTandem( 'gameCountingAreaNode' ),
-        top: equationNode.bottom + 20
+        tandem: tandem.createTandem( 'gameCountingAreaNode' )
       } );
 
       const kittensLayerNode = new KittensLayerNode( level.countingObjects, gameCountingAreaNode, {
@@ -142,7 +159,7 @@
         tandem: tandem.createTandem( 'tenFrameButton' ),
         // touchAreaXDilation: buttonVBoxSpacing / 2,
         // touchAreaYDilation: buttonVBoxSpacing / 2,
-        right: gameCountingAreaNode.left,
+        left: layoutBounds.left + NumberPairsConstants.SCREEN_VIEW_X_MARGIN,
         top: gameCountingAreaNode.top,
         listener: () => {
           this.interruptSubtreeInput();
@@ -164,8 +181,8 @@
     // Buttons row: Check / Next
     const checkButton = new TextPushButton( 'Check', {
       tandem: tandem.createTandem( 'checkButton' ),
-      right: layoutBounds.right - 100,
-      top: layoutBounds.top + 100,
+      right: NumberPairsConstants.COUNTING_AREA_BOUNDS.right,
+      bottom: BUTTONS_TOP ? numberButtonGrid.top - 20 : NumberPairsConstants.COUNTING_AREA_BOUNDS.top - NumberPairsConstants.COUNTING_AREA_Y_MARGIN,
       listener: () => {
         const guess = numberButtonGrid.getSelectedNumber();
         if ( guess !== null ) {
Index: js/game/view/NumberButtonGrid.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/game/view/NumberButtonGrid.ts b/js/game/view/NumberButtonGrid.ts
--- a/js/game/view/NumberButtonGrid.ts	(revision 8bedae19fec7839cadec686bccb4b16baae5ce2a)
+++ b/js/game/view/NumberButtonGrid.ts	(date 1758672397441)
@@ -1,7 +1,7 @@
 // Copyright 2025, University of Colorado Boulder
 
 /**
- * NumberButtonGrid lays out identically sized number buttons in one or two rows.
+ * NumberButtonGrid lays out identically sized number buttons in one or two columns.
  * Row 1: 0..10
  * Row 2: 11..20 (11 is under 1; 0 has nothing under it)
  *
@@ -18,49 +18,62 @@
 import PhetFont from '../../../../scenery-phet/js/PhetFont.js';
 import AlignGroup from '../../../../scenery/js/layout/constraints/AlignGroup.js';
 import AlignBox from '../../../../scenery/js/layout/nodes/AlignBox.js';
-import Node, { NodeOptions } from '../../../../scenery/js/nodes/Node.js';
 import Text from '../../../../scenery/js/nodes/Text.js';
 import BooleanRectangularStickyToggleButton from '../../../../sun/js/buttons/BooleanRectangularStickyToggleButton.js';
-import Tandem from '../../../../tandem/js/Tandem.js';
 import numberPairs from '../../numberPairs.js';
-import InputRange from '../model/InputRange.js';
+import GridBox, { GridBoxOptions } from '../../../../scenery/js/layout/nodes/GridBox.js';
+import WithRequired from '../../../../phet-core/js/types/WithRequired.js';
+import StrictOmit from '../../../../phet-core/js/types/StrictOmit.js';
+import Range from '../../../../dot/js/Range.js';
+import optionize, { EmptySelfOptions } from '../../../../phet-core/js/optionize.js';
+import Node from '../../../../scenery/js/nodes/Node.js';
 
-const BUTTON_SIZE = new Dimension2( 60, 60 );
-const X_SPACING = 12;
-const Y_SPACING = 12;
-const FONT = new PhetFont( 24 );
+const BUTTON_SIZE = new Dimension2( 40, 40 );
+const X_SPACING = 10;
+const Y_SPACING = 10;
+const FONT = new PhetFont( 20 );
 
-export default class NumberButtonGrid extends Node {
-  public readonly anySelectedProperty: BooleanProperty;
-  public readonly selectedIsEnabledProperty: BooleanProperty;
+type SelfOptions = EmptySelfOptions;
+type NumberButtonGridOptions = SelfOptions & WithRequired<GridBoxOptions, 'tandem'> & StrictOmit<GridBoxOptions, 'columns' | 'rows' | 'children'>;
+export default class NumberButtonGrid extends GridBox {
+  public readonly anySelectedProperty: Property<boolean>;
+  public readonly selectedIsEnabledProperty: Property<boolean>;
 
-  private readonly buttonStates: BooleanProperty[];
-  private readonly buttons: BooleanRectangularStickyToggleButton[];
+  // All the button pressed state Properties, in the same order as buttons and buttonValues.
+  private readonly buttonPressedProperties: Property<boolean>[];
+  private readonly buttons: Node[];
   private readonly buttonValues: number[];
 
-  public constructor( selectedNumberProperty: Property<number | null>, range: InputRange, guessedNumbers: ObservableArray<number>, tandem: Tandem, providedOptions?: NodeOptions ) {
-    super();
+  public constructor( selectedNumberProperty: Property<number | null>, range: Range, guessedNumbers: ObservableArray<number>, providedOptions: NumberButtonGridOptions ) {
 
     const alignGroup = new AlignGroup();
-    this.buttonStates = [];
-    this.buttons = [];
-    this.buttonValues = [];
-    this.anySelectedProperty = new BooleanProperty( false );
-    this.selectedIsEnabledProperty = new BooleanProperty( false );
+
+    const tenColumn: Node[] = [];
+    const twentyColumn: Node[] = [];
+
+    // TODO: Should this be renamed to buttonSelectedProperties? to match the language used below? https://github.com/phetsims/number-pairs/issues/208
+    //   but there is also documentation that uses the term "pressed" so not sure which is better.
+    const buttonPressedProperties: Property<boolean>[] = [];
+    const buttons: Node[] = [];
+    const buttonValues: number[] = [];
+    const anySelectedProperty = new BooleanProperty( false );
+
+    // TODO: What is this tracking? https://github.com/phetsims/number-pairs/issues/208
+    //   it appears to be something about whether the button that was pressed is enabled or not?
+    const selectedIsEnabledProperty = new BooleanProperty( false );
     const updateSelectionState = () => {
 
       // true if any button is pressed in
-      const anySelected = this.buttonStates.some( p => p.value );
-      this.anySelectedProperty.value = anySelected;
+      anySelectedProperty.value = buttonPressedProperties.some( pressedProperty => pressedProperty.value );
 
       // currently selected number (or null)
-      const selectedIndex = this.buttonStates.findIndex( state => state.value );
-      selectedNumberProperty.value = selectedIndex >= 0 ? this.buttonValues[ selectedIndex ] : null;
-      this.selectedIsEnabledProperty.value = selectedIndex >= 0 ? this.buttons[ selectedIndex ].enabledProperty.value : false;
+      const selectedIndex = buttonPressedProperties.findIndex( state => state.value );
+      selectedNumberProperty.value = selectedIndex >= 0 ? buttonValues[ selectedIndex ] : null;
+      selectedIsEnabledProperty.value = selectedIndex >= 0 ? buttons[ selectedIndex ].enabledProperty.value : false;
     };
 
     // Helper to create a fixed-size button for a given number, placed at a given grid position.
-    const createButton = ( value: number, columnIndex: number, rowIndex: number ) => {
+    const createButton = ( value: number ) => {
 
       const label = new Text( value, { font: FONT } );
       const labelBox = new AlignBox( label, {
@@ -69,29 +82,29 @@
         yAlign: 'center'
       } );
 
-      const stateProperty = new BooleanProperty( false );
-      this.buttonStates.push( stateProperty );
-      this.buttonValues.push( value );
+      const isPressedProperty = new BooleanProperty( false );
+      buttonPressedProperties.push( isPressedProperty );
+      buttonValues.push( value );
 
-      const button = new BooleanRectangularStickyToggleButton( stateProperty, {
+      const button = new BooleanRectangularStickyToggleButton( isPressedProperty, {
         accessibleName: value.toString(),
-        tandem: tandem.createTandem( `number${value}Button` ),
+        tandem: providedOptions.tandem.createTandem( `number${value}Button` ),
         content: labelBox,
         size: BUTTON_SIZE,
         baseColor: '#f7d9a5'
       } );
 
-      this.buttons.push( button );
+      buttons.push( button );
 
-      button.left = columnIndex * ( BUTTON_SIZE.width + X_SPACING );
-      button.top = rowIndex * ( BUTTON_SIZE.height + Y_SPACING );
+      // We want the buttons in ascending order from top to bottom, so we unshift to the front of the array.
+      value <= 10 ? tenColumn.unshift( button ) : twentyColumn.unshift( button );
 
       // When this button is pressed in (true), pop out all other buttons
-      stateProperty.lazyLink( isDown => {
-        if ( isDown ) {
-          this.buttonStates.forEach( p => {
-            if ( p !== stateProperty ) {
-              p.value = false;
+      isPressedProperty.lazyLink( isPressed => {
+        if ( isPressed ) {
+          buttonPressedProperties.forEach( pressedProperty => {
+            if ( pressedProperty !== isPressedProperty ) {
+              pressedProperty.value = false;
             }
           } );
         }
@@ -101,31 +114,32 @@
       return button;
     };
 
-    // Row 1: 0..10
-    for ( let n = 0; n <= 10; n++ ) {
-      this.addChild( createButton( n, n, 0 ) );
-    }
+    // We want to be inclusive of the max value, so we do max + 1 here.
+    _.times( range.max + 1, i => createButton( i ) );
 
-    // Row 2: 11..20 (11 under 1; 0 has nothing under it)
-    if ( range === 'zeroToTwenty' ) {
-      for ( let n = 11; n <= 20; n++ ) {
-        const columnIndex = n - 10; // 11->1 ... 20->10
-        this.addChild( createButton( n, columnIndex, 1 ) );
-      }
-    }
-
+    const options = optionize<NumberButtonGridOptions, SelfOptions, GridBoxOptions>()( {
+      columns: [ tenColumn, twentyColumn ],
+      xSpacing: X_SPACING,
+      ySpacing: Y_SPACING
+    }, providedOptions );
+    super( options );
+    this.buttonPressedProperties = buttonPressedProperties;
+    this.buttons = buttons;
+    this.buttonValues = buttonValues;
+    this.anySelectedProperty = anySelectedProperty;
+    this.selectedIsEnabledProperty = selectedIsEnabledProperty;
 
     // React to guessed numbers from the model by disabling those buttons
     const applyGuessedNumbers = () => {
       for ( let i = 0; i < this.buttonValues.length; i++ ) {
         const value = this.buttonValues[ i ];
-        const shouldEnable = !guessedNumbers.includes( value );
-        this.buttons[ i ].enabledProperty.value = shouldEnable;
+
+        // Disable buttons for guessed numbers
+        this.buttons[ i ].enabledProperty.value = !guessedNumbers.includes( value );
       }
       // Update aggregate selection state (including enabled state)
-      const anySelected = this.buttonStates.some( p => p.value );
-      this.anySelectedProperty.value = anySelected;
-      const selectedIndex = this.buttonStates.findIndex( state => state.value );
+      this.anySelectedProperty.value = this.buttonPressedProperties.some( pressedProperty => pressedProperty.value );
+      const selectedIndex = this.buttonPressedProperties.findIndex( pressedProperty => pressedProperty.value );
       selectedNumberProperty.value = selectedIndex >= 0 ? this.buttonValues[ selectedIndex ] : null;
       this.selectedIsEnabledProperty.value = selectedIndex >= 0 ? this.buttons[ selectedIndex ].enabledProperty.value : false;
     };
@@ -134,15 +148,13 @@
     guessedNumbers.elementAddedEmitter.addListener( applyGuessedNumbers );
     guessedNumbers.elementRemovedEmitter.addListener( applyGuessedNumbers );
     guessedNumbers.lengthProperty.link( applyGuessedNumbers );
-
-    this.mutate( providedOptions );
   }
 
   /**
    * Gets the currently selected number, or null if none selected.
    */
   public getSelectedNumber(): number | null {
-    const selectedIndex = this.buttonStates.findIndex( state => state.value );
+    const selectedIndex = this.buttonPressedProperties.findIndex( pressedProperty => pressedProperty.value );
     return selectedIndex >= 0 ? this.buttonValues[ selectedIndex ] : null;
   }
 
@@ -159,8 +171,8 @@
    * Resets all buttons to their initial state (enabled and unselected).
    */
   public resetAll(): void {
-    this.buttonStates.forEach( state => {
-      state.value = false;
+    this.buttonPressedProperties.forEach( pressedProperty => {
+      pressedProperty.value = false;
     } );
     this.buttons.forEach( button => {
       button.enabledProperty.value = true;
Index: js/common/NumberPairsConstants.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/NumberPairsConstants.ts b/js/common/NumberPairsConstants.ts
--- a/js/common/NumberPairsConstants.ts	(revision 8bedae19fec7839cadec686bccb4b16baae5ce2a)
+++ b/js/common/NumberPairsConstants.ts	(date 1758672525847)
@@ -17,7 +17,7 @@
 
 const TEN_TOTAL_RANGE = new Range( 0, 10 );
 const TWENTY_TOTAL_RANGE = new Range( 11, 20 );
-const COUNTING_AREA_X_MARGIN = 80;
+const COUNTING_AREA_X_MARGIN = 120;
 const COUNTING_AREA_MIN_Y = ScreenView.DEFAULT_LAYOUT_BOUNDS.minY + 200;
 const COUNTING_AREA_BOUNDS = new Bounds2( ScreenView.DEFAULT_LAYOUT_BOUNDS.minX + COUNTING_AREA_X_MARGIN,
   COUNTING_AREA_MIN_Y, ScreenView.DEFAULT_LAYOUT_BOUNDS.maxX - COUNTING_AREA_X_MARGIN, COUNTING_AREA_MIN_Y + 340 );
```

</details>

**Comment by samreid** [comment]
I implemented the layout change in https://github.com/phetsims/number-pairs/issues/213, not sure if there are other TODOs or changes we should take from the patch above. @marlitas can you please advise, or close the issue if nothing more to do here?

**Comment by marlitas** [comment]
I went ahead and refactored to use GridBox in NumberButtonGrid. I still have a question about `stateProperty` which is a `BooleanProperty`. The name "stateProperty" sounds like an enumeration to me and I had a difficult time understanding what true or false indicates in it's usage. I would recommend a rename, although I'm not sure what it should be. Perhaps it's tracking wether the button is selected or not?

**Comment by samreid** [comment]
After the change, the `NumberButtonGrid` no longer has the first focused element correct (10 is focused, but should be 0) and the focus order is no longer correct. `stateProperty` is the `BooleanProperty` indicating whether a particular toggle button is pressed (true) or unpressed (false). In the parent class `BooleanRectangularStickyToggleButton` it is simply called `booleanProperty`
